spring.application.name=ProfileService
server.port=8088

spring.datasource.url=jdbc:mysql://localhost:3306/profile_service_db
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

azure.storage.container-name:user-image

# gRPC server configuration
grpc.server.port=9088

grpc.client.upload-service.address=static://localhost:9000
grpc.client.upload-service.negotiationType=PLAINTEXT

grpc.client.auth-service.address=static://localhost:9091
grpc.client.auth-service.negotiationType=PLAINTEXT