spring.application.name=UploadFileService
server.port=8000

azure.storage.connection-string=DefaultEndpointsProtocol=https;\
  AccountName=shopapp;\
  AccountKey=ZicaZPve24tBipqvd+DmwGh8synSp8khdMtOXHFStRqSI2+B/6SRA7RsBsJ0koWHVnC3WcpfdpfV+AStvjTL7Q==;\
  EndpointSuffix=core.windows.net

auth.username= authUsername
auth.password= authPassword