spring.application.name=ApiGateway
server.port=8888

app.api-prefix=/api/v1

# gRPC configuration for auth service
auth.service.grpc.host=localhost
auth.service.grpc.port=9091

# gRPC configuration for profile service
profile.service.grpc.host=localhost
profile.service.grpc.port=9088

jwt.secret=myVeryStrongSecretKeyThatIsLongEnough123456


# Route for auth-service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=${app.api-prefix}/auth/**

# Route for profile-service-user
spring.cloud.gateway.routes[1].id=profile-service
spring.cloud.gateway.routes[1].uri=http://localhost:8088
spring.cloud.gateway.routes[1].predicates[0]=Path=${app.api-prefix}/profile/**,${app.api-prefix}/address/**

# Route for product-service-product
spring.cloud.gateway.routes[2].id=product-service
spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=${app.api-prefix}/products/**,${app.api-prefix}/categories/**,${app.api-prefix}/brands/**

# Route for cart-service
spring.cloud.gateway.routes[3].id=cart-service
spring.cloud.gateway.routes[3].uri=http://localhost:8083
spring.cloud.gateway.routes[3].predicates[0]=Path=${app.api-prefix}/cart/**

# Route for order-service
spring.cloud.gateway.routes[4].id=order-service
spring.cloud.gateway.routes[4].uri=http://localhost:8084
spring.cloud.gateway.routes[4].predicates[0]=Path=${app.api-prefix}/order/**

# Router for payment-service
spring.cloud.gateway.routes[5].id=payment-service
spring.cloud.gateway.routes[5].uri=http://localhost:8085
spring.cloud.gateway.routes[5].predicates[0]=Path=${app.api-prefix}/payment/**

# Route for chat-service
spring.cloud.gateway.routes[6].id=chat-service
spring.cloud.gateway.routes[6].uri=http://localhost:8086
spring.cloud.gateway.routes[6].predicates[0]=Path=${app.api-prefix}/chat/**

# Route for Search Service
spring.cloud.gateway.routes[7].id=search-service
spring.cloud.gateway.routes[7].uri=http://localhost:8089
spring.cloud.gateway.routes[7].predicates[0]=Path=${app.api-prefix}/search/**

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging.level.org.springframework.web=DEBUG
logging.level.com.example=DEBUG
logging.level.org.springframework.security=DEBUG
