
spring.application.name=AuthenticationService
server.port=8081
spring.cloud.compatibility-verifier.enabled=false

logging.level.org.springframework.security=DEBUG

# gRPC server configuration
grpc.server.port=9091

# gRPC client configuration
grpc.client.profile-service.address=static://localhost:9098
grpc.client.profile-service.negotiationType=PLAINTEXT

grpc.client.upload-service.address=static://localhost:9000
grpc.client.upload-service.negotiationType=PLAINTEXT

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/auth_service_db
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT
jwt.secret=myVeryStrongSecretKeyThatIsLongEnough123456
jwt.valid-duration=300000
jwt.refresh-valid-duration=604800000

# OAuth2 providers
google.client-id=684085962364-7rehml07an0j5hffa3l98u3a23sk9ju1.apps.googleusercontent.com
google.client-secret=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
google.redirect-uri=http://localhost:3000/authenticate

facebook.client-id=691094630187412
facebook.client-secret=e91656c09fb3f2b37461168f2db9e76e
facebook.redirect-uri=http://localhost:3000/authenticate

# VNPay
vnp.tmn-code=XA75FX7S
vnp.hash-secret=VEO6AI63WE5T17MAML2XW06FKSTYRNSV
vnp.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.return-url=http://localhost:3000/
vnp.timeout=15

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.com.example=DEBUG

# Producer
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
