spring.application.name=notification-service
server.port=8087
spring.cloud.compatibility-verifier.enabled=false

# Kafka
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.auto-offset-reset=earliest

#spring.kafka.bootstrap-servers=kafka-namespace-tri.servicebus.windows.net:9093
#spring.kafka.properties.security.protocol=SASL_SSL
#spring.kafka.properties.sasl.mechanism=PLAIN
#spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://kafka-namespace-tri.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xK/lBTcY8fGIpEAIyJm0VtcfoDmZEfltG+AEhK8CbKo=";
#spring.kafka.consumer.auto-offset-reset=earliest


# Consumer JSON
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# MailJet
mailjet.apiUrl=https://api.mailjet.com/v3.1
mailjet.apiKey=f747f396704a9470c729523f51362432
mailjet.secretKey=4c7d3dd49f0d48931ac3da4966db9fab

mailjet.sender=nguyenhuutri99.sgu@gmail.com

mailjet.message.template=7643730
mailjet.template.ordersuccess=7643729
mailjet.template.paymentsuccess=7643739
mailjet.template.usercreated=7643732
mailjet.template.userupdated=7643745
mailjet.template.passwordchanged=7643744
mailjet.template.ordercancelled=7780374

# Thymeleaf for Email Templates

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
